name: Build LaTeX document
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"


permissions:
  contents: write


jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: ${{!startsWith(github.event.head_commit.message, 'skip-build') }}
    timeout-minutes: 20
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      - name: Download Fonts I
        uses: robinraju/release-downloader@v1.8
        with:
          tag: "Latex-lite"
          # Choose what fonts you need from https://github.com/MohammadRaziei/fonts/releases
          repository: "mohammadraziei/fonts"
          fileName: "fonts.zip"
          out-file-path: "fonts"
          extract: true

      - name: Download Fonts II-A
        uses: robinraju/release-downloader@v1.8
        with:
          tag: "fa-pro-archive"
          # Choose what fonts you need from https://github.com/MohammadRaziei/fonts/releases
          repository: "mohammadraziei/fonts"
          fileName: "IranSans.zip"
          out-file-path: "fonts"
          extract: true

      - name: Download Fonts II-B
        run: |
          mv fonts/Iran\ Sans/IRANSans\ v5.0/WebFonts/fonts/ttf/*.ttf fonts
          rm -rf fonts/Iran\ Sans



      - name: Preview files
        run: tree --du -shaC .


      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        continue-on-error: true
        with:
          root_file: "./*.tex"
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_fonts: ./fonts/*.ttf

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: "./*.pdf"
          if-no-files-found: error

  publish_pdf:
    name: Publish PDF
    needs: [ build_latex ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: PDF

      - name: Determine release type
        id: release_type
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/v.*$ ]]; then
            echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "IS_TAG=true" >> $GITHUB_ENV
          else
            echo "RELEASE_NAME=__preview__" >> $GITHUB_ENV
            echo "IS_TAG=false" >> $GITHUB_ENV
          fi
        shell: bash # Use bash for all platforms

      - name: Create or update release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_NAME }}
          name: ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: ${{ env.IS_TAG == 'false' }}
          files: "./*.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}

